import Foundation
import SwiftUI

nonisolated enum OrderStatus: String, Codable, CaseIterable, Identifiable, Sendable {
    case consulta
    case cotizacion
    case esperandoAnticipo
    case confirmado
    case porPreparar
    case horneado
    case decorando
    case terminado
    case entregado
    case cancelado

    var id: String { rawValue }

    var label: String {
        switch self {
        case .consulta: return "Consulta"
        case .cotizacion: return "Cotización enviada"
        case .esperandoAnticipo: return "Esperando anticipo"
        case .confirmado: return "Confirmado"
        case .porPreparar: return "Por preparar"
        case .horneado: return "Horneado"
        case .decorando: return "Decorando"
        case .terminado: return "Terminado"
        case .entregado: return "Entregado"
        case .cancelado: return "Cancelado"
        }
    }

    var tint: Color {
        switch self {
        case .consulta: return Theme.accentDeep
        case .cotizacion: return Color(red: 0.55, green: 0.45, blue: 0.72)
        case .esperandoAnticipo: return Theme.gold
        case .confirmado, .terminado: return Theme.sage
        case .porPreparar, .horneado, .decorando: return Color(red: 0.36, green: 0.55, blue: 0.72)
        case .entregado: return Theme.secondaryInk
        case .cancelado: return Color(red: 0.72, green: 0.33, blue: 0.33)
        }
    }

    /// Orders that must appear in the production board.
    var isProduction: Bool {
        switch self {
        case .confirmado, .porPreparar, .horneado, .decorando, .terminado: return true
        default: return false
        }
    }

    var isOpen: Bool { self != .entregado && self != .cancelado }
}

/// One material required to produce an order. Fully editable during production.
nonisolated struct ProductionMaterial: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var name: String = ""
    var quantity: Double = 0
    var unit: MeasureUnit = .gram
    var isReady: Bool = false
    var notes: String = ""
    /// True when generated by the calculator, false when added by hand.
    var isAutomatic: Bool = true
    var inventoryItemID: UUID?
    var symbol: String = "circle"

    var quantityLabel: String {
        unit == .unit
            ? "\(Fmt.number(quantity)) \(quantity == 1 ? "unidad" : "unidades")"
            : "\(Fmt.number(quantity)) \(unit.shortLabel)"
    }
}

nonisolated struct ChecklistStep: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var title: String = ""
    var detail: String = ""
    var isDone: Bool = false
}

nonisolated enum PaymentMethod: String, Codable, CaseIterable, Identifiable, Sendable {
    case efectivo
    case transferencia
    case tarjeta
    case otro

    var id: String { rawValue }
    var label: String {
        switch self {
        case .efectivo: return "Efectivo"
        case .transferencia: return "Transferencia"
        case .tarjeta: return "Tarjeta"
        case .otro: return "Otro"
        }
    }
}

/// An Instagram order, from the first message to the finished delivery.
nonisolated struct Order: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var clientName: String = ""
    var instagram: String = ""
    var phone: String = ""
    var createdAt: Date = Date()
    var deliveryDate: Date = Date()
    var status: OrderStatus = .consulta

    var cakeTitle: String = ""
    var flavor: String = ""
    var recipeID: UUID?
    var spec: CakeSpec = CakeSpec()
    var design: String = ""
    var referenceImageURL: String = ""
    var dedication: String = ""

    /// Stored optional so older saved files keep decoding after the update.
    var referenceFiles: [OrderAttachment]?
    var pinnedAttachmentID: UUID?

    var price: Double = 0
    var deposit: Double = 0
    var paymentMethod: PaymentMethod = .transferencia
    var address: String = ""
    var shippingCost: Double = 0
    var extraCosts: Double = 0
    var notes: String = ""

    var materials: [ProductionMaterial] = []
    var checklist: [ChecklistStep] = []
    var inventoryDeducted: Bool = false

    /// Photos and documents attached to the order, newest last.
    var attachments: [OrderAttachment] {
        get { referenceFiles ?? [] }
        set { referenceFiles = newValue }
    }

    var photoAttachments: [OrderAttachment] { attachments.filter(\.isPhoto) }
    var documentAttachments: [OrderAttachment] { attachments.filter { !$0.isPhoto } }

    /// The reference the chef wants to keep visible while decorating.
    var pinnedAttachment: OrderAttachment? {
        if let pinnedAttachmentID, let match = attachments.first(where: { $0.id == pinnedAttachmentID }) {
            return match
        }
        return photoAttachments.first
    }

    var balance: Double { max(price + shippingCost - deposit, 0) }
    var isPaid: Bool { balance <= 0.001 && price > 0 }

    var displayTitle: String {
        cakeTitle.isEmpty ? spec.summaryLabel : cakeTitle
    }

    var readyMaterials: Int { materials.filter(\.isReady).count }

    var checklistProgress: Double {
        guard !checklist.isEmpty else { return 0 }
        return Double(checklist.filter(\.isDone).count) / Double(checklist.count)
    }

    var initials: String {
        let parts = clientName.split(separator: " ").prefix(2)
        let letters = parts.compactMap { $0.first }.map(String.init)
        return letters.joined().uppercased()
    }
}

nonisolated struct Client: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var name: String = ""
    var instagram: String = ""
    var phone: String = ""
    var notes: String = ""
    var favoriteFlavor: String = ""
}

nonisolated enum CatalogCategory: String, Codable, CaseIterable, Identifiable, Sendable {
    case personalizados
    case clasicos
    case cupcakes
    case miniCakes
    case postres
    case otros

    var id: String { rawValue }
    var label: String {
        switch self {
        case .personalizados: return "Pasteles personalizados"
        case .clasicos: return "Pasteles clásicos"
        case .cupcakes: return "Cupcakes"
        case .miniCakes: return "Mini cakes"
        case .postres: return "Postres"
        case .otros: return "Otros"
        }
    }
}

nonisolated struct CatalogProduct: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var name: String = ""
    var category: CatalogCategory = .clasicos
    var detail: String = ""
    var photoURL: String = ""
    var basePrice: Double = 0
    var sizes: String = ""
    var flavors: String = ""
    var servings: Int = 0
}

/// A saved calculation the chef can reuse later.
nonisolated struct SavedCalculation: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var name: String = ""
    var createdAt: Date = Date()
    var spec: CakeSpec = CakeSpec()
    var recipeID: UUID?
}
